# Generated by Django 4.1.1 on 2022-10-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='درباره'),
        ),
    ]
