# Generated by Django 4.1.1 on 2023-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_description_user_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
