# Generated by Django 4.1.1 on 2022-09-29 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آیپی')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='news_type',
            field=models.BooleanField(blank=True, choices=[(False, 'خبر معمولی'), (True, 'خبر ویژه')], default=False,
                                      help_text='<div id="id_short_description_helptext" class="help">اگر خبر شما جزو اخبار مهم و فوری می باشد می توانید آن را در دسته<strong style="margin:5px">ویژه</strong>قرار دهید.</div>',
                                      null=True, verbose_name='نوع خبر'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(default=datetime.datetime.today,
                                   help_text='این متن به عنوان خلاصه ای از محتوای مقاله شما در حداکثر یک بند می باشد.',
                                   verbose_name='پیشنمایش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(choices=[(False, 'منتشر نشده'), (True, 'منتشر شده')], default=True,
                                      verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(False, 'غیرفعال'), (True, 'فعال')], default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media/images/articles', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='عنوانی که برای خبر ها می گذارید نباید تکراری باشد.', max_length=250,
                                   verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='ArticleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, editable=False, related_name='hits', through='blog.ArticleHit',
                                         to='blog.ipaddress', verbose_name='بازدید ها'),
        ),
    ]
