# Generated by Django 4.1.1 on 2022-09-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_ipaddress_article_news_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'منتشر نشده')], default=True,
                                      verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(True, 'فعال'), (False, 'غیرفعال')], default=True, verbose_name='وضعیت'),
        ),
    ]
