# Generated by Django 4.1.1 on 2022-09-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_alter_article_news_type_alter_article_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(True, 'فعال'), (False, 'غیرفعال')], default=True, verbose_name='وضعیت'),
        ),
    ]
