# Generated by Django 4.1.1 on 2022-09-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'منتشر نشده')], default=True,
                                      verbose_name='وضعیت'),
        ),
    ]
