# Generated by Django 4.1.1 on 2022-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_alter_article_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(choices=[(False, 'منتشر نشده'), (True, 'منتشر شده')], default=True,
                                      verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(False, 'غیرفعال'), (True, 'فعال')], default=True, verbose_name='وضعیت'),
        ),
    ]
