# Generated by Django 4.1.1 on 2022-10-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0011_alter_article_news_type_alter_article_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'منتشر نشده')], default=True,
                                      verbose_name='وضعیت'),
        ),
    ]
