# Generated by Django 4.1.1 on 2022-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0012_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(choices=[(False, 'منتشر نشده'), (True, 'منتشر شده')], default=True,
                                      verbose_name='وضعیت'),
        ),
    ]
