# Generated by Django 4.1.1 on 2022-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0014_alter_article_news_type_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(True, 'فعال'), (False, 'غیرفعال')], default=True, verbose_name='وضعیت'),
        ),
    ]
