# Generated by Django 4.1.1 on 2022-10-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0019_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(choices=[(False, 'منتشر نشده'), (True, 'منتشر شده')], default=True,
                                      verbose_name='وضعیت'),
        ),
    ]
